### ISSUE TITLE
Looks like ":100:" is showing up in script output as "100"

### ISSUE THREAD

**Issue by rick** [muan/megamoji#5]
![megamoji](https://cloud.githubusercontent.com/assets/6259/10894137/4dfcb8b8-8172-11e5-9229-84caa57a8c2d.png)

:heart:

**Comment by muan** [comment]
haiiii odd, i can't reproduce this, in chrome at least, which seems to be what you're using? are there perhaps steps for reproducing this?

**Comment by rick** [comment]
I can't seem to reproduce this now (and I believe this is the same browser - Chrome on OSX Version 46.0.2490.86 (64-bit)). I tried a number of variations on ordering, etc.

Going to call this "fixed".  :sparkles:
